### ISSUE TITLE
Source for Ubuntu Focal kernel submodule has changed

### ISSUE THREAD

**Issue by SHexplorer** [kiler129/relax-intel-rmrr#5]
The source for the git server has changed. See
`curl -k "https://git.proxmox.com/?p=mirror_ubuntu-focal-kernel.git;a=snapshot;h=$(git submodule status submodules/ubuntu-focal | cut -c 2-41);sf=tgz" --output kernel.tgz`

You get now a "403 - Snapshots not allowed" as error message in the kernel.tgz (html code)

PS: This "hack" is really nice. Too bad it will not get in the official kernel.

**Comment by kiler129** [comment]
After doing some research it looks like Proxmox deliberately blocked this (perhaps due to server load or space?). I will need to find a better method of obtaining the base kernel. In the meantime https://github.com/kiler129/relax-intel-rmrr/pull/8 this is patching the issue - it will work, just more slowly.
